### ISSUE TITLE
Temporary storage location for kgml files

### ISSUE THREAD

**Issue by JamesPino** [LoLab-VU/Magine#2]
Right now it checks to see if a directory called KEGG exists. If not it creates it and stores all KGML files there. When reading in, it appends a KEGG directory before each pathway file. Ideally it would create a directory that was project specific but wouldn't just add a 'KEGG/' and assume you did not change location.

**Comment by alubbock** [comment]
If the files are temporary, `tempdir.mkdtemp()` would be the way to go. If not, a user-supplied path or environment variable would work.

If you have a lot of user-configurable options that should persist each time you run magine, take a look at configparser: https://docs.python.org/2/library/configparser.html and appdirs: https://pypi.python.org/pypi/appdirs/1.2.0 for storing information in a configuration file (it might be overkill for this application, but worth knowing about in any case).
