### ISSUE TITLE
Create standard tests for package

### ISSUE THREAD

**Issue by JamesPino** [LoLab-VU/Magine#3]
I have began to create tests, but not according to any specific format. I don't know the best practice for writing unit tests. Should they be doc tests, unittets, py tests? @alubbock any suggestions on standards or best practices?

**Comment by alubbock** [comment]
The library we use for PySB is nosetests, which will run doc tests and unit tests. Use doc tests for typical example(s) for each function, and unit tests in a tests/ directory for less obvious usage, testing corner cases (unusual but valid inputs, like empty arrays, all zeroes in an array etc.) and for testing expected failures (supplying functions with arguments that should generate a particular exception, to make sure it checks inputs as expected).

Have a look at some of the PySB tests for inspiration: https://github.com/pysb/pysb/tree/master/pysb/tests
